
toBibtex(citation("tidyverse"))
toBibtex(citation("magrittr")) 
toBibtex(citation("janitor")) 
toBibtex(citation("lubridate")) 
toBibtex(citation("scales"))  
toBibtex(citation("zoo"))  
toBibtex(citation("stargazer"))  
toBibtex(citation("RSQLite"))  
toBibtex(citation("ggplot2")) 
toBibtex(citation("ggrepel"))  
toBibtex(citation("ggalt"))  
toBibtex(citation("ggdark"))  
toBibtex(citation("patchwork"))  
toBibtex(citation("showtext"))  
toBibtex(citation("reactable"))  
toBibtex(citation("kableExtra"))  

